### ISSUE TITLE
Avante bad keymappings

### ISSUE THREAD

**Issue by ctretyak** [AstroNvim/astrocommunity#1257]
### Is your feature related to a problem?

I've started to use Avante. It's really great. But I have some troubles with key bindings.

They start on [c] key that already used by vim motions [c]ange. E.g. I cannot use standard vim [cc] binding. I know, that I can use [S] instead of [cc], but it is occupied by another popular vim sneaky plugin.

FYI @aarnphm 

### Describe the new feature

I'd like to consider to change first letter or add leader key to all AvanteConflict* commands

### Additional context

https://github.com/AstroNvim/astrocommunity/tree/main/lua/astrocommunity/completion/avante-nvim

**Comment by Uzaaft** [comment]
Feel free to open a PR.

**Comment by mehalter** [comment]
I opened a PR that fixes this. It doesn't change the bindings, but it does configure them correctly so that they are only usable bindings when changes are available and you are reviewing them and not while just editing text normally. This resolves the conflict while leaving the very "common sense" like bindings for accepting changes
