### ISSUE TITLE
clang_format - why is it in the java pack?

### ISSUE THREAD

**Issue by jay-babu** [AstroNvim/astrocommunity#500]
https://github.com/AstroNvim/astrocommunity/blob/aeecada9c9abaa7961a74528caf637ba7683b2b1/lua/astrocommunity/pack/java/init.lua#L21

**Comment by Uzaaft** [comment]
Take a look at the clang_format docs. :)

**Comment by jay-babu** [comment]
These docs: https://clang.llvm.org/docs/ClangFormat.html? doesn't answer the question why clang_format over something else

**Comment by Uzaaft** [comment]
It’s a Java formater. What formater would you’ve prefered to have?

**Comment by jay-babu** [comment]
google_java_format is my choice

**Comment by jay-babu** [comment]
I would prefer nothing tbh. I removed it for me. https://github.com/jay-babu/dotfiles/commit/d921e359bd13dae470117d0361849ba0938c134a

**Comment by Uzaaft** [comment]
I think most beginner users expect some kind of formatter.

**Comment by Uzaaft** [comment]
@luxus  He asked a question, and I answered it. Going to close this issue now.  If you think we should remove the formatter, or swap it out @jay-babu , I'm open to both of those, just open a PR. :)

**Comment by CMOISDEAD** [comment]
I also decided to disable clang_format, because when saving a java file it sometimes moves the cursor from one point to another, which is a bit annoying.

I don't know if it's something in my configuration, but for example when a method only contains one instruction when saving clang_format converts it to a single line method and automatically jdtls reverts it back to the way it was, which results in the cursor ending up just below the method or at the end of the file.

**Comment by Uzaaft** [comment]
@CMOISDEAD If what you're advocating for is to change the formatter, a better way is to just open a PR instead of posting on an old issue.
